### ISSUE TITLE
[MongoDB] Brainstorm about what database to use

### ISSUE THREAD

**Issue by LizaTheCount** [HvA-Robotics/circl-wood#5]
(Create UML design/layout?)
• Firebase
• mySQL
• MongoDB << **Winner**
• (any others?)

**Comment by LizaTheCount** [comment]
8 different databases with their pros and cons:
https://www.keycdn.com/blog/popular-databases

**Comment by FrankRidder** [comment]
https://scalegrid.io/blog/2019-database-trends-sql-vs-nosql-top-databases-single-vs-multiple-database-use/

**Comment by FrankRidder** [comment]
We came to the conclusion to use MongoDB. We chose this because it is one of the mosted used non-sql databases. We chose a non-sql database because we are not going to use relationships and we like the horizontally scalability of non-sql.
